remote_theme             : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "mint" 

# Site Settings

title                    : "LRP"
title_separator          : "-"
name                     : "Lukas Holzner"
description              : "**L**ukas **R**andom **P**rojects"
url                      : "http://lholz.de"
baseurl                  : "/"
repository               : "MeisterGig/lholz.de"



# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache


include:
  - .htaccess
  - _pages
exclude:
  - README


# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development


# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: true
      share: true
      related: true